-- Config blocks
config {
    type: "view",
    schema: constants.SOURCE,
    description: "GA4データソース ストリーミングデータ",
    tags: ["daily", "source"]
}


-- Query blocks
with ga AS(
SELECT *
FROM                    
	${ref(constants.GA4_INTRADAY_TABLE)}
WHERE
    _table_suffix BETWEEN
        (SELECT FORMAT_DATE("%Y%m%d",PARSE_DATE("%Y%m%d", MAX(event_date)) + 1) FROM ${ref("ga4_fixed_events")})
        AND FORMAT_DATE("%Y%m%d",(CURRENT_DATE('Asia/Tokyo')))

)
SELECT *
FROM ga
